"""Booking main tables create

Revision ID: 5bbf6d01adb2
Revises: 272fa4443fb5
Create Date: 2023-06-19 20:28:48.942281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbf6d01adb2'
down_revision = '272fa4443fb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check-in', sa.String(), nullable=False),
    sa.Column('departure', sa.String(), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartment_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.TIMESTAMP(), nullable=False),
    sa.Column('end', sa.TIMESTAMP(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('name', sa.String(), nullable=False)
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('distance_to_sea', sa.String(), nullable=False),
    sa.Column('ia_active', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.Column('apartment_rule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_rule_id'], ['apartment_rule.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type_apartment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start', sa.TIMESTAMP(), nullable=False),
    sa.Column('end', sa.TIMESTAMP(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('paid_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('apartment')
    op.drop_table('type_apartment')
    op.drop_table('tag')
    op.drop_table('city')
    op.drop_table('apartment_rules')
    op.drop_table('apartment_rule')
    # ### end Alembic commands ###
