"""refactor apart

Revision ID: 674ebbbde430
Revises: a76cddec6b24
Create Date: 2023-06-19 21:22:37.840510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674ebbbde430'
down_revision = 'a76cddec6b24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
