"""add in appartment model new fields

Revision ID: 7e891f861fb0
Revises: d41ba2eb5dae
Create Date: 2023-06-20 13:11:25.037657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e891f861fb0'
down_revision = 'd41ba2eb5dae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('quantity_room', sa.Integer(), nullable=True))
    op.add_column('apartment', sa.Column('square', sa.Integer(), nullable=True))
    op.add_column('apartment', sa.Column('pledge', sa.Integer(), nullable=True))
    op.add_column('apartment', sa.Column('max_num_of_guests', sa.Integer(), nullable=True))
    op.add_column('apartment', sa.Column('storey_of_house', sa.Integer(), nullable=True))
    op.add_column('apartment', sa.Column('storey', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment', 'storey')
    op.drop_column('apartment', 'storey_of_house')
    op.drop_column('apartment', 'max_num_of_guests')
    op.drop_column('apartment', 'pledge')
    op.drop_column('apartment', 'square')
    op.drop_column('apartment', 'quantity_room')
    # ### end Alembic commands ###
