"""refactor apart

Revision ID: d41ba2eb5dae
Revises: 674ebbbde430
Create Date: 2023-06-19 21:32:31.226724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd41ba2eb5dae'
down_revision = '674ebbbde430'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartment', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('apartment', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('apartment', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('apartment', 'distance_to_sea',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('apartment_rule', 'check-in',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('apartment_rule', 'departure',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('apartment_rule', 'min_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('booking', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('booking', 'end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('booking', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('booking', 'paid_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('price', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('price', 'end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('price', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tag', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('type_apartment', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('type_apartment', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tag', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('price', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('price', 'end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('price', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('booking', 'paid_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('booking', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('booking', 'end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('booking', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('apartment_rule', 'min_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('apartment_rule', 'departure',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('apartment_rule', 'check-in',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('apartment', 'distance_to_sea',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('apartment', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('apartment', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('apartment', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
